# Generated by Django 4.2.26 on 2025-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_book_subject_rename_category_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_done',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='is_done',
            new_name='status',
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
